apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: eks-cni
  name: awsekscni
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: cni-metrics-port
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: aws-node
