apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: gameserver
  name: servicemonitor-custom
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metric
    targetPort: 8080
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - dev
  selector:
    matchLabels: {}
